name: tflint
title: tflint
contact: https://github.com/tingdahl/tflint
website: https://github.com/tingdahl/tflint
license: MPL-2.0
summary: Linter for terraform definitions
description: >
      The tflint from https://github.com/terraform-linters/tflint . 
      The the snap should follow the upstream project.
version: git
source-code: https://github.com/tingdahl/tflint.git
grade: stable
base: core22

confinement: strict

apps:
  tflint:
    command: tflint
    plugs:
      - home
      - removable-media
      - network-bind
parts:
  tflint:
    plugin: go
    build-environment:
      - GOBIN: "$CRAFT_PRIME"
    build-snaps: [go]
    source-type: git
    override-build: make install
    source: https://github.com/tingdahl/tflint.git
